Repository PWEB-3-3-2022/front, pull requests merged in 2022-05, with the labels that each got.

#59 Feat/videoplayer
  src/global.css
  src/lib/MosaicTile.svelte
  src/lib/Popup.svelte
Labels: feature

#68 Reworked logout system
  src/account.js
  src/api.js
  src/lib/AccountDropdown.svelte
  src/pages/Account.svelte
Labels: feature, security

#70 Correctly handle profiles as an object
  src/account.js
  src/lib/AccountDropdown.svelte
  src/pages/Account.svelte
  src/pages/Home.svelte
  src/pages/ProfileSelection.svelte
Labels: bug

#73 Fixed a little bug with created date in Account page
  src/pages/Account.svelte
Labels: bug

#74 Use media play api
  src/api.js
  src/lib/MosaicTile.svelte
  src/lib/Popup.svelte
Labels: feature
