Repository PWEB-3-3-2022/front, pull requests merged in 2022-03, with the labels that each got.

#5 Created menu, sidebar and "logo", needs improvements and optimisation
  src/App.svelte
  src/lib/Hamburger.svelte
  src/lib/Logo.svelte
  src/lib/MosaicTile.svelte
  src/lib/Navbar.svelte
  src/lib/Sidebar.svelte
Labels: enhancement

#13 Add new tcflix logo
  src/assets/svelte.png
  src/assets/tcflix_logo.png
  src/lib/Logo.svelte
Labels: feature

#32 Add routing
  package.json
  pnpm-lock.yaml
  src/App.svelte
  src/lib/Logo.svelte
  src/lib/Sidebar.svelte
  src/pages/About.svelte
  src/pages/Home.svelte
Labels: feature

#37 Search on key pressed
  src/lib/Searchbar.svelte
Labels: feature

#36 Working footer
  src/App.svelte
  src/lib/Footer.svelte
Labels: feature

#43 Add favicon
  index.html
  public/favicon.ico
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/site.webmanifest
Labels: style

#41 Added the Global CSS fix
  src/App.svelte
  src/lib/Footer.svelte
Labels: bug

#34 Login base
  src/api.js
  src/lib/Login_button.svelte
  src/lib/Navbar.svelte
  src/lib/Searchbar.svelte
  src/pages/Login.svelte
Labels: feature

#45 Account dropdown
  src/api.js
  src/lib/AccountDropdown.svelte
  src/lib/Navbar.svelte
  src/pages/Login.svelte
  src/pages/Register.svelte
Labels: feature

#54 Populate homepage, update styling everywhere
  src/api.js
  src/global.css
  src/lib/Footer.svelte
  src/lib/Mosaic.svelte
  src/lib/MosaicTile.svelte
  src/lib/Navbar.svelte
  src/lib/Searchbar.svelte
  src/pages/Account.svelte
  src/pages/Home.svelte
  src/pages/Search.svelte
Labels: feature
